### ISSUE TITLE
Morning & Afternoon changeover

### ISSUE THREAD

**Issue by m1geo** [m1geo/WordClock#3]
The morning/afternoon changeover isn't right at mid day because the 'to hour' 12 wraps to 13, and the clock defaults to afternoon.

Test these special cases.

**Comment by m1geo** [comment]
"It is xx to twelve in the morning" when approaching mid day.

**Comment by m1geo** [comment]
"it is five to one in the evening" at 12:56pm. 1pm

**Comment by m1geo** [comment]
Test commit b503e2c0c8b65af92779e2c4611ea25e9ba7c24e for fixes for this.

**Comment by rmc47** [comment]
Seems legit.
